In [47]:
import pandas as pd

In [48]:
pan = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\featuresPAN.tsv", sep="\t")
pan.columns = pan.columns.str.strip()
pan['gene_id'] = [gene.split(".")[0].strip() for gene in pan['gene_id']]
pan.head(5)

                   gene_name          gene_id
0  TNFRSF4                    ENSG00000186827
1  TNFRSF18                   ENSG00000186891
2  ATAD3B                     ENSG00000160072
3  ENSG00000260179.1          ENSG00000260179
4  ENSG00000234396.3          ENSG00000234396

In [49]:
pan = pan[['gene_id','gene_name']]

In [64]:
pan.to_csv('featuresPANcorrigido.tsv',header=None, sep="\t", index=False)

In [63]:
pan.head(5)

           gene_id                  gene_name
0  ENSG00000186827  TNFRSF4
1  ENSG00000186891  TNFRSF18
2  ENSG00000160072  ATAD3B
3  ENSG00000260179  ENSG00000260179.1
4  ENSG00000234396  ENSG00000234396.3

In [52]:
M = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\featuresM.tsv\features.tsv", sep="\t", header=None)
M[0] = M[0].str.strip()
M.head(5)

                 0             1                2
0  ENSG00000243485    MIR1302-10  Gene Expression
1  ENSG00000237613       FAM138A  Gene Expression
2  ENSG00000186092         OR4F5  Gene Expression
3  ENSG00000238009  RP11-34P13.7  Gene Expression
4  ENSG00000239945  RP11-34P13.8  Gene Expression

In [53]:


pan.head(5)

           gene_id                  gene_name
0  ENSG00000186827  TNFRSF4
1  ENSG00000186891  TNFRSF18
2  ENSG00000160072  ATAD3B
3  ENSG00000260179  ENSG00000260179.1
4  ENSG00000234396  ENSG00000234396.3

In [54]:
pan_set = set(pan["gene_id"])
m_set = set(M[0])
interseccao = pan_set & m_set
print(len(interseccao))

30836

In [55]:
list(pan_set)[:5]

['ENSG00000207304',
 'ENSG00000267415',
 'ENSG00000131779',
 'ENSG00000170509',
 'ENSG00000267378']

In [56]:
fuji = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\features.tsv",sep="\t",header=None)
fuji[0] = fuji[0].str.strip()
fuji.head(5)

                 0            1                2
0  ENSG00000243485  MIR1302-2HG  Gene Expression
1  ENSG00000237613      FAM138A  Gene Expression
2  ENSG00000186092        OR4F5  Gene Expression
3  ENSG00000238009   AL627309.1  Gene Expression
4  ENSG00000239945   AL627309.3  Gene Expression

In [57]:
fuji_set = set(fuji[0])

In [58]:
inter_pan_fuj =pan_set & fuji_set
print(len(inter_pan_fuj))

36476

In [59]:
diferenca_pan_fuji = pan_set - fuji_set
print(len(diferenca_pan_fuji))

25065

In [60]:
diferenca_pan_M = pan_set - m_set
print(len(diferenca_pan_M))

30705

In [61]:
pan_features = pd.DataFrame(pan_set)
pan_features.head(5)

                 0
0  ENSG00000207304
1  ENSG00000267415
2  ENSG00000131779
3  ENSG00000170509
4  ENSG00000267378

In [62]:
pan_features.to_csv('featuresPANcorrigido.tsv',header=None, sep="\t", index=False)